version: 2

models:
    - name: popular song
      description: Bandcamp music genres statistic
      columns:
          - name: longest_song
            description: song with longest duration
          - name: genre 
            description: genre name
          - name: total_artists 
            description: Number of artist
          - name: total_albums 
            description: Number of albums
          - name: popularity
            description: index popularity