version: 2

models:
    - name: total_album_artist_song_genre
      description: total statistic of album, artist, song, genre, duration

models:
    - name: most_longest_duration_song_artist_genre
      description: most longest duration song, artist, and genre

models:
    - name: most_shortest_duration_song_artist_genre
      description: most short duration song, artist, and genre

models:
    - name: most_popular_genre
      description: most popular genre

models:
    - name: less_popular_genre
      description: less popular genre
