version: 2

sources:
  - name: staging
    database: project-de-zoomcamp-418214
    schema: project_spotify_dataset
    tables:
      - name: spotify

models:
  - name: stg_spotify
    columns:
      - name: track_id
        description: "foreign key"
      - name: album_name
        description: "Name of the album"
      - name: artists_name
        description: "Name of the artist"
      - name: track_name
        description: "Name of the song"
      - name: popularity
        description: "Popularity of the song"
      - name: duration_minute
        description: "Duration of the song"
      - name: genre
        description: "Genre of the song"